### ISSUE TITLE
Is this just used to open a browser window?

### ISSUE THREAD

**Issue by dwjohnston** [yoshuawuyts/markdown-to-medium#20]
I just had a bit of a play with this - seems to work - but it opens a browser window where I have to manually hit publish. 

Is that the intended functionality? 

I'm really wanting it to publish directly.

**Comment by yoshuawuyts** [comment]
> I just had a bit of a play with this - seems to work - but it opens a browser window where I have to manually hit publish.

It is; you might want to touch up any inconsistencies (which are likely to exist)
